### ISSUE TITLE
Unable to setup Valkey

### ISSUE THREAD

**Issue by gaby** [shogo82148/actions-setup-redis#1021]
@shogo82148 When running `valkey` only version 7.2 works. Using `8.x`, `8.0`, `8.0.0` currently fails to setup with this error: 

```
Error: Error: unable to get latest version
```

The current version is out of date too, it should be 8.0.1

Example workflow:

```yaml
on:
    push:
        branches:
            - master
            - main
        paths:
            - 'valkey/**'
    pull_request:
        paths:
            - 'valkey/**'

name: "Tests Valkey"
jobs:
    Tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version:
                    - 1.23.x
                valkey:
                    - '7.x'
                    - '8.x'
        steps:
            -   name: Fetch Repository
                uses: actions/checkout@v4

            -   name: Setup Valkey
                uses: shogo82148/actions-setup-redis@v1
                with:
                    distribution: 'valkey'
                    redis-version: ${{ matrix.valkey }}
                    auto-start: 'false'
                    redis-port: '6379'
                    redis-tls-port: '6380'
```

Related to https://github.com/gofiber/storage/pull/1538
