### ISSUE TITLE
add unixsocket option

### ISSUE THREAD

**Issue by kostya** [shogo82148/actions-setup-redis#330]
Hi, this is nice action sets. My project request unixsocket option. Is it possible to add it, or allow to write custom config file(or part of file)?

i think best solution would be custom config like this:
```yaml
    steps:
      - uses: actions/checkout@v2
      - name: Setup redis
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: ${{ matrix.redis }}
          auto-start: "false"
          custom_config: "unixsocket /tmp/sock\n#..."

```
