### ISSUE TITLE
Question to add/pass config parameters

### ISSUE THREAD

**Issue by benblub** [shogo82148/actions-setup-redis#429]
How can i pass/add to config things like

maxmemory 2mb
maxmemory-policy allkeys-lru

**Comment by shogo82148** [comment]
You can configure the `redis-conf` option.
for example:

```yaml
- uses: shogo82148/actions-setup-redis@v1
  with:
    redis-version: '6.x'
    redis-conf: |
      maxmemory 2mb
      maxmemory-policy allkeys-lru
```
