### ISSUE TITLE
Can't open openssl.cnf for reading, No such file or directory

### ISSUE THREAD

**Issue by tommymonk** [shogo82148/actions-setup-redis#693]
I'm getting this error with the following config against shogo82148/actions-setup-redis@v1 on a linux self-hosted runner.

```
      - name: setup redis server dependencies
        run: |
          apt-get -y install zstd
        
      - name: setup redis server
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: '6.x'
```

![MicrosoftTeams-image](https://user-images.githubusercontent.com/574131/207403896-e513c3f7-ecd1-4a23-b688-fc7d4b4d3124.png)
