### ISSUE TITLE
Failing `redis-cli` after upgrade to v1.35.0

### ISSUE THREAD

**Issue by dmitryax** [shogo82148/actions-setup-redis#958]
After upgrading to v1.35.0, the following steps started failing on `ubuntu-20.04` runners:

```
      - uses: shogo82148/actions-setup-redis@v1
        with:
          auto-start: false
      - run: redis-cli ping
```

```
Run redis-cli ping
  redis-cli ping
  shell: /usr/bin/bash -e {0}
  env:
    GO_VERSION: 1.[2](https://github.com/signalfx/splunk-otel-collector/actions/runs/10275513852/job/28434381324?pr=5192#step:15:2)1.12
    TEST_OUTPUT: integration-test-binary-integration-ubuntu-20.04.out
redis-cli: error while loading shared libraries: libssl.so.[3](https://github.com/signalfx/splunk-otel-collector/actions/runs/10275513852/job/28434381324?pr=5192#step:15:3): cannot open shared object file: No such file or directory
```

It works fine on `ubuntu-22.04` and `ubuntu-24.04`.

Looks like an issue similar to https://github.com/shogo82148/actions-setup-redis/issues/555
